// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import EventFormController from "controllers/event_form_controller"
application.register("event-form", EventFormController)

import ThemeController from "controllers/theme_controller"
application.register("theme", ThemeController)
