if Rails.env.production?
  ENV['RECAPTCHA_PUBLIC_KEY']  = "6LfQYwEAAAAAAKlcAvQyWiUuhK2MsLWdAg2NetNG"
  ENV['RECAPTCHA_PRIVATE_KEY'] = "6LfQYwEAAAAAALns-mpDvMoNBUbnxlQW16E91ZRU"
else
  ENV['RECAPTCHA_PUBLIC_KEY']  = "6LfQYwEAAAAAAKlcAvQyWiUuhK2MsLWdAg2NetNG" #development
  ENV['RECAPTCHA_PRIVATE_KEY'] = "6LfQYwEAAAAAALns-mpDvMoNBUbnxlQW16E91ZRU" #development
end